proxies:
  enabled: true
  type: http
  path: proxies.txt
  timeout: 5000
  order: random # (e.g. linear, random)

tokens:
  # Do not change this unless you know what you're doing.
  regex: "[A-Za-z0-9]{24}.[A-Za-z0-9]{6}.[A-Za-z0-9]{27}"
  path: tokens.txt

settings:
  verbose: false
  remove_duplicates: true
  threads: 200
  timeout: 5000
  delay: 1000