config:
  proxies:
    - enabled: true
    - type: http
    - path: proxies.txt
    - timeout: 5000
    - rotating: false

  tokens:
    # Do not change this unless you know what you're doing.
    - regex: ^(mfa.[A-Za-z_0-9]+|[MN][A-Za-z\d]{23}\.[\w-]{6}\.[\w-]{27})$
    - path: tokens.txt

  settings:
    - threads: 200
    - timeout: 5000
    - delay: 1000
