proxies:
  enabled: true
  type: http
  path: proxies.txt
  timeout: 5000
  order: random # (e.g. linear, random)

tokens:
  # Do not change this unless you know what you're doing.
  regex: "[\w-]{24}\.[\w-]{6}\.[\w-]{25,110}"
  path: tokens.txt

settings:
  verbose: false
  remove_duplicates: true
  threads: 200
  timeout: 5000
  delay: 1000